[package]
name        = "vitte-dap"
description = "Adaptateur Debug (DAP) pour Vitte : protocole, handlers et serveur stdio."

version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }
readme       = { workspace = true }

keywords   = ["vitte", "dap", "debugger", "protocol"]
categories = ["development-tools", "debugging", "compilers"]

[lib]
name = "vitte_dap"
# tu as choisi un lib en `src/dap.rs`
path = "src/dap.rs"

[[bin]]
name = "vitte-dap"
path = "src/main.rs"

[features]
# Par défaut : std + logs
default = ["std", "trace"]
std     = []

# Traces/logs
trace = ["dep:log", "dep:env_logger"]

[dependencies]
# internes (si besoin, ajoute vitte-vm pour le pilotage runtime)
vitte-core = { path = "../vitte-core", version = "0.1.0" }

# externes (héritent du workspace quand dispo)
serde       = { workspace = true }
serde_json  = { workspace = true }
clap        = { workspace = true, features = ["derive"] }
log         = { workspace = true, optional = true }
env_logger  = { workspace = true, optional = true }
anyhow      = { workspace = true }
color-eyre  = "0.6"

# async runtime pour le serveur stdio (ou TCP)
tokio       = { version = "1", features = ["rt-multi-thread", "macros", "io-std", "io-util", "sync", "time"] }

[dev-dependencies]
pretty_assertions = { workspace = true }

[package.metadata.docs.rs]
all-features = true

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all                      = "warn"
pedantic                 = "warn"
nursery                  = "warn"
module_name_repetitions  = "allow"
too_many_lines           = "allow"
doc_markdown             = "allow"
